#ifndef _ZOMBIE_A_ANIM_H_
#define _ZOMBIE_A_ANIM_H_

typedef enum
{
	ZOMBIE_A_DEATH,
	ZOMBIE_A_ATTACK,
	ZOMBIE_A_WALKING,
	ZOMBIE_A_RUNNING,
	ZOMBIE_A_IDLE,
	ZOMBIE_A_ANIM_MAX
}ZOMBIE_A_ANIM_LIST;

#endif // !_ENEMY_ANIM_H_
